@startmindmap
* Архитектор

right side 

** Hard skills
***_ Шаблоны проектирования систем
***_ Облака 
***_ Сети
***_ Хранения данных
***_ Стриминг данных
***_ Мониторинг
***_ Биг Дата
***_ Машинное обучение
***_ Веб технологии
***_ Мобильные технологии
***_ Безопасность

left side 

** Роли и обязанности
***_ Скрам Мастер
****_ Управление поставками
****_ Церемонии
****_ Ускорение разработки
***_ Бизнес аналитик
****_ Функциональные требования
****_ Нефункциональные требования
****_ Ограничения
***_ Технический писатель
****_ Написание архитектурных документов
*****_ Документ Архитектуры решений
*****_ Архитектурное Ревью
****_ Архитектурные диаграммы
*****_ Views и View Points
*****_ C4
*****_ Use Cases
*****_ Sequence
***_ Разработчик
****_ Написание Proof of Concepts
****_ Написание инструментов
***_ Консультант
****_ Анализ решений
****_ Создание оценок


@endmindmap
