@startmindmap
* Architect

right side 

** Hard skills
***_ [[https://www.amazon.com/Software-Architecture-Practice-3rd-Engineering/dp/0321815734 System design patterns and tactics]]
****_ Avaiability
****_ Maintainability
****_ Performance
****_ Scalability
****_ Security
***_ Cloud technologies
****_ Providers
*****_ [[https://cloud.google.com/gcp Google Cloud Platform]]
*****_ [[https://azure.microsoft.com/en-us/ Azure]]
*****_ [[https://aws.amazon.com/ Amazon Web Services]] 
****_ Storage
*****_ Relational Databases
*****_ DBaaS
*****_ S3 like storage
****_ Compute
*****_ VMs
*****_ Containers
*****_ Functions
****_ Network
****_ Elasticity
***_ Data storage
***_ Data streaming
***_ Monitoring
***_ Big Data & Data Engineering
***_ Machine Learning
***_ Web Technologies
****_ React
****_ Angular
****_ Vue.js
***_ Mobile Technologies
****_ Native Android
****_ Native iOS
****_ Hybrid apps
****_ React-Native
****_ Flutter

** Soft skills
***_ Public speaking
***_ [[https://www.coursera.org/learn/negotiation-skills Negotiating]]
***_ Conflict management
***_ [[https://www.youtube.com/watch?v=cFdCzN7RYbw Persuading]]
***_ [[https://www.amazon.com/Practical-Project-Stakeholder-Management-Comprehensive/dp/1549517929 Stakeholder management]]
***_ Time management
***_ Business communication

left side 

** Roles and responsibilities
***_ Scrum Master
****_ Delivery Management
****_ Communication plans
****_ Project schedule
****_ [[https://en.wikipedia.org/wiki/Theory_of_constraints Theory of constraints]]
***_ Business analytics
****_ Functional Requirements
****_ Quality Attributes
****_ Constraints
***_ Technical Writer
****_ Architecture Documents
*****_ Solution Architecture Document
*****_ Architecture Review
*****_ [[https://github.com/joelparkerhenderson/architecture-decision-record Archictecture Decision Log]]
****_ Architecture Diagrams
*****_ Views и View Points
*****_ C4
*****_ Use Cases
*****_ Sequence
***_ Developer
****_ Proof of Concepts
****_ Tools
****_ Unurgent business features
***_ Consultancy
****_ Solution comparison
****_ Estimations
****_ Strategy advisory


@endmindmap
